dist: xenial
language: node_js
#node_js: stable
node_js: 14.8.0
addons:
  ## Ubuntu 16+ (libgconf-2-4) does not install this dependency by default, so we need to install it ourselves
  packages: libgconf-2-4  // try without
#  chrome: stable // try without
  ## firefox: "49.0" or latest version
#  firefox: latest // try without
#  edge: latest // try without

cache:
  npm: true
  directories: ~/.cache ~/.npm

install: npm ci

#before_script:

defaults: &defaults
  script:
    - npm run serve & npm test
    - npm run cy:run -- --record --parallel --group $STAGE_NAME
    - kill $(jobs -p) || true
jobs:
  include:
    - stage: test
      env:
        - STAGE_NAME="1x-electron on Travis CI"
      <<: *defaults
#    - stage: test
#      env:
#        - STAGE_NAME="1x-electron on Travis CI"
#      <<: *defaults
#    - stage: test
#      env:
#        - STAGE_NAME="1x-electron on Travis CI"
#      <<: *defaults
#    - stage: test
#      env:
#        - STAGE_NAME="1x-electron on Travis CI"
#      <<: *defaults
    ## run tests in parallel by including several test jobs with same name variable
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults


