dist:
  - trusty
language:
  - node_js
node_js:
  - stable
#cache:
#  directories:
#    - ~/.npm
#    - ~/.cache

addons:
  chrome: stable

  override:
    - npm ci
    - npm run cy:verify
    - npm google-chrome --version
    - 
before_script:
  - 'export DISPLAY=:99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3
defaults: &defaults
  script:
    - npm run serve & npm test
    - kill $(jobs -p) || true
jobs:
  include:
    ## we have multiple jobs to execute using just a single stage
    - stage: test
      env:
        - STAGE_NAME="1x-electron on Travis CI"
      <<: *defaults
    # run tests in parallel by including several test jobs with same name variable
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
