dist:
  - trusty
language:
  - node_js
node_js:
  - stable
#cache:
#  directories:
#    - ~/.npm
#    - ~/.cache
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

  override:
    - npm ci
    - npm run cy:verify
#    - google-chrome --version
defaults: &defaults
  script:
    - npm run serve & npm test
    - kill $(jobs -p) || true
jobs:
  include:
    ## we have multiple jobs to execute using just a single stage
    - stage: test
      env:
        - STAGE_NAME="1x-electron on Travis CI"
      <<: *defaults
    # run tests in parallel by including several test jobs with same name variable
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
