dist: xenial
language: node_js
node_js: stable
addons:
  ## Ubuntu 16+ (libgconf-2-4) does not install this dependency by default, so we need to install it ourselves
  packages: libgconf-2-4
  chrome: stable
  ## firefox: "49.0" or latest version
  firefox: latest

cache:
  npm: true
  directories: ~/.cache

#    - ~/.npm
#    - ~/.cache

#cache:
#  bundler: true
#    - node -v
#    - npm i -g
#    - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
#    - LATEST_CHROMEDRIVER_VERSION=`curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE`
#    - curl https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip -O
#    - unzip chromedriver_linux64.zip -d ~/bin

#override: npm ci
install: npm ci

#  - npm ci
#  - npm run cy:verify


#before_script:

defaults: &defaults
  script:
    - npm run serve & npm test
    - kill $(jobs -p) || true
jobs:
  include:
    ## we have multiple jobs to execute using just a single stage
    - stage: test
      env:
        - STAGE_NAME="1x-electron on Travis CI"
      <<: *defaults
    ## run tests in parallel by including several test jobs with same name variable
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults

script:
  # print all Travis environment variables for debugging
  - $(npm bin)/print-env TRAVIS
  - $(npm bin)/print-env COMMIT_INFO_SHA
  - $(npm bin)/cypress run --record
