dist: xenial
language: node_js
node_js: stable
addons:
  ## Ubuntu 16+ (libgconf-2-4) does not install this dependency by default, so we need to install it ourselves
  packages: libgconf-2-4
  chrome: stable
  ## firefox: "49.0" or latest version
  firefox: latest

cache:
  npm: true
  directories: ~/.cache

install: npm ci

#before_script:

defaults: &defaults
  script:
    - npm run serve & npm test
    - kill $(jobs -p) || true
jobs:
  include:
#    ## we have multiple jobs to execute using just a single stage
#    - stage: test
#      env:
#        - STAGE_NAME="1x-electron on Travis CI"
#      <<: *defaults
    ## run tests in parallel by including several test jobs with same name variable
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults
    - stage: test
      env:
        - STAGE_NAME="4x-electron on Travis CI"
      <<: *defaults

script:
  - echo ">>>>>>>>> CONTAINERS LOG FILES <<<<<<<<<<<<"
  # print all Travis environment variables for debugging
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG

after_failure:
  echo " >>>>> testsummary log file <<<< "
  - cat MSBuild_*.failure.txt
